<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>asm</string>
		<string>inc</string>
	</array>
	<key>name</key>
	<string>MasmAssembly</string>
	<key>patterns</key>
	<array>
		<?单行注释?>
		<dict>
			<key>match</key>
			<string>;.*$</string>
			<key>name</key>
			<string>comment.line</string>
		</dict>
		<?注释块?>
		<dict>
			<key>begin</key>
			<string>comment\t\*</string>
			<key>end</key>
			<string>\t\*</string>
			<key>name</key>
			<string>comment.block</string>
		</dict>
		<?变量声明?>
		<dict>
			<key>match</key>
			<string>\b(byte|sbyte|word|sword|dword|sdword|fword|qword|tbyte|db|dw|dd|dq|real4|real8|real10|even|align|org|label|offset|addr|dup)\b</string>
			<key>name</key>
			<string>entity.directive.data.allocation</string>
		</dict>
		<?简化段声明?>
		<dict>
			<key>match</key>
			<string>(^|\s)\.(code|const|data|data\?|dosseg|exit|fardata|fardata\?|model|stack|startup)$</string>
			<key>name</key>
			<string>entity.directive.segment.simplified</string>
		</dict>
		<?段声明?>
		<dict>
			<key>match</key>
			<string>(^|\s)(\.alpha|gruop|segment|\.seq)$</string>
			<key>name</key>
			<string>entity.directive.segment</string>
		</dict>
		<?条件汇编?>
		<dict>
			<key>match</key>
			<string>(^|\s)(else|elseif|elseif2|if|if2|ifb|ifnb|ifdef|ifndef|ifdif|ifdifi|ife|ifidn|ifidni)\s</string>
			<key>name</key>
			<string>entity.assembly.conditional</string>
		</dict>
		<?循环汇编?>
		<dict>
			<key>match</key>
			<string>(^|\s)(for|forc|repeat|while)\s</string>
			<key>name</key>
			<string>entity.assembly.repeat</string>
		</dict>
		
		<?执行流控制?>
		<dict>
			<key>match</key>
			<string>(^|\s)\.(break|continue|else|elseif|endif|endw|if|repeat|until|untilcxz|while)\s</string>
			<key>name</key>
			<string>entity.directive.control.flow</string>
		</dict>
		<?定义?>
		<dict>
			<key>match</key>
			<string>(^|\s)(equ|textequ)\s</string>
			<key>name</key>
			<string>entity.directive.equate</string>
		</dict>
		<?宏?>
		<dict>
			<key>match</key>
			<string>(^|\s)(endm|exitm|goto|local|macro|purge)\s</string>
			<key>name</key>
			<string>entity.directive.macro</string>
		</dict>
		<?函数?>
		<dict>
			<key>match</key>
			<string>(^|\s)(endp|invoke|proc|proto)\s</string>
			<key>name</key>
			<string>entity.directive.procedure</string>
		</dict>
		<?处理器?>
		<dict>
			<key>match</key>
			<string>(^|\s)\.(386|386p|387|486|486p|586|586p|686|686p|k3d|mmx|xmm)\s</string>
			<key>name</key>
			<string>entity.directive.processor</string>
		</dict>
		<?可见域?>
		<dict>
			<key>match</key>
			<string>(^|\s)(comm|extern|externdef|public)\s</string>
			<key>name</key>
			<string>entity.directive.scope</string>
		</dict>
		<?杂项?>
		<dict>
			<key>match</key>
			<string>(^|\s)(assume|ends|record|struct|typedef|union|high|high32|highword|length|lengthof|low|low32|lowword|opattr|ptr|short|size|sizeof|this|type|\.model|flat|stdcall|option|casemap|none|carry\?|overflow\?|parity\?|sign\?|zero\?)\b</string>
			<key>name</key>
			<string>entity.directive.misc</string>
		</dict>
		<?标签?>
		<dict>
			<key>match</key>
			<string>^.*:$</string>
			<key>name</key>
			<string>entity.name.label</string>
			<?冒号后面不能有别的?>
		</dict>
		<?数字?>
		<dict>
			<key>match</key>
			<string>\b[0-9][0-9a-fA-F]*+h?\b</string>
			<key>name</key>
			<string>constant.numeric</string>
		</dict>
		<?字符串匹配?>
		<dict>
			<key>begin</key>
			<string>["']</string>
			<key>beginCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.begin.jwasm</string>
				</dict>
			</dict>
			<key>end</key>
			<string>["']</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.definition.string.end.jwasm</string>
				</dict>
			</dict>
			<key>name</key>
			<string>string.quoted.asm</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#string_escaped_char</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#string_placeholder</string>
				</dict>
			</array>
		</dict>
		<?包含文件?>
		<dict>
			<key>begin</key>
			<string>^\s*(includelib|include)</string>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.control.import.include.jwasm</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>meta.preprocessor.jwasm.include</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>\s*</string>
					<key>beginCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.begin.jwasm</string>
						</dict>
					</dict>
					<key>end</key>
					<string>$</string>
					<key>endCaptures</key>
					<dict>
						<key>0</key>
						<dict>
							<key>name</key>
							<string>punctuation.definition.string.end.jwasm</string>
						</dict>
					</dict>
					<key>name</key>
					<string>keyword.control.import.include.jwasm</string>
				</dict>
			</array>
		</dict>
		<?fpu指令?>
		<dict>
			<key>match</key>
			<string>^\s*(f2xm1|fabs|fadd|faddp|fbld|fbstp|fchs|fclex|fcom|fcomp|fcompp|fdecstp|fdisi|fdiv|fdivp|fdivr|fdivrp|feni|ffree|fiadd|ficom|ficomp|fidiv|fidivr|fild|fimul|fincstp|finit|fist|fistp|fisub|fisubr|fld|fld1|fldcw|fldenv|fldenvw|fldl2e|fldl2t|fldlg2|fldln2|fldpi|fldz|fmul|fmulp|fnclex|fndisi|fneni|fninit|fnop|fnsave|fnsavew|fnstcw|fnstenv|fnstenvw|fnstsw|fpatan|fprem|fptan|frndint|frstor|frstorw|fsave|fsavew|fscale|fsqrt|fst|fstcw|fstenv|fstenvw|fstp|fstsw|fsub|fsubp|fsubr|fsubrp|ftst|fwait|fxam|fxch|fxtract|fyl2x|fyl2xp1|fsetpm|fcos|fldenvd|fnsaved|fnstenvd|fprem1|frstord|fsaved|fsin|fsincos|fstenvd|fucom|fucomp|fucompp|fcomi|fcomip|fucomi|fucomip|ffreep|fcmovb|fcmove|fcmovbe|fcmovu|fcmovnb|fcmovne|fcmovnbe|fcmovnu)\s</string>
			<key>name</key>
			<string>instruction.fpu</string>
		</dict>
		<?字符串指令?>
		<dict>
			<key>match</key>
			<string>^\s*(cmpsb|cmpsw|cmpsd|cmpsq|movsb|movsw|movsd|movsq|scasb|scasw|scasd|scasq|stosb|stosw|stosd|stosq|lodsb|lodsw|lodsd|lodsq)\s</string>
			<key>name</key>
			<string>instruction.string</string>
		</dict>
		<?cmov指令?>
		<dict>
			<key>match</key>
			<string>^\s*(cmovo|cmovno|cmovb|cmovc|cmovnae|cmovae|cmovnb|cmovnc|cmove|cmovz|cmovne|cmovnz|cmovbe|cmovna|cmova|cmovnbe|cmovs|cmovns|cmovp|cmovpe|cmovnp|cmovpo|cmovl|cmovnge|cmovge|cmovnl|cmovle|cmovng|cmovg|cmovnle)\s</string>
			<key>name</key>
			<string>instruction.cmov</string>
		</dict>
		<?标志指令?>
		<dict>
			<key>match</key>
			<string>^\s*(clc|cld|stc|std|cmc|lahf|sahf)\s</string>
			<key>name</key>
			<string>instruction.flag</string>
		</dict>
		<?前缀指令?>
		<dict>
			<key>match</key>
			<string>^\s*(lock|rep|repe|repz|repne|repnz)\s</string>
			<key>name</key>
			<string>instruction.prefix</string>
		</dict>
		<?堆栈指令?>
		<dict>
			<key>match</key>
			<string>^\s*(push|pop|pushad|popad|pushf|popf|pushfd|popfd|pushfq|popfq)\s</string>
			<key>name</key>
			<string>instruction.stack</string>
		</dict>
		<?内存操作指令?>
		<dict>
			<key>match</key>
			<string>^\s*(lea|mov|movsx|movsxd|movzx|xlatb|bound|xchg|xadd|cmpxchg|cmpxchg8b|cmpxchg16b)\s</string>
			<key>name</key>
			<string>instruction.memory</string>
		</dict>
		<?运算单元指令?>
		<dict>
			<key>match</key>
			<string>^\s*(add|sub|adc|sbb|neg|cmp|inc|dec|and|or|xor|not|test|shl|shr|sal|sar|shld|shrd|rol|ror|rcl|rcr|cbw|cwd|cwde|cdq|cdqe|cqo|bsf|bsr|bt|btc|btr|bts|idiv|imul|div|mul|bswap|nop)\s</string>
			<key>name</key>
			<string>instruction.alu</string>
		</dict>
		<?控制流指令?>
		<dict>
			<key>match</key>
			<string>^\s*(ja|jae|jb|jbe|jc|jcxz|je|jg|jge|jl|jle|jmp|jna|jnae|jnb|jnbe|jnc|jne|jng|jnge|jnl|jnle|jno|jnp|jns|jnz|jo|jp|jpe|jpo|js|jz|jcxz|jecxz|jrcxz|loop|loope|loopne|loopz|loopnz|call|ret)\s</string>
			<key>name</key>
			<string>instruction.flow</string>
		</dict>
		<?BCD码指令?>
		<dict>
			<key>match</key>
			<string>^\s*(aaa|aad|aam|aas|daa|das)\s</string>
			<key>name</key>
			<string>instruction.bcd</string>
		</dict>
		<?寄存器?>
		<dict>
			<key>match</key>
			<string>\b(eax|ebx|ecx|edx|esi|edi|ebp|esp|al|ah|bl|bh|cl|ch|dl|dh|ax|bx|cx|dx|sil|dil|bpl|si|di|bp|sp|rax|rcx|rdx|rbx|rsp|rbp|rsi|rdi|r8b|r9b|r10b|r11b|r12b|r13b|r14b|r15b|r8w|r9w|r10w|r11w|r12w|r13w|r14w|r15w|r8|r9|r10|r11|r12|r13|r14|r15|st0|st1|st2|st3|st4|st5|st6|st7|mm0|mm1|mm2|mm3|mm4|mm5|mm6|mm7|xmm0|xmm1|xmm2|xmm3|xmm4|xmm5|xmm6|xmm7|xmm8|xmm9|xmm10|xmm11|xmm12|xmm13|xmm14|xmm15|ymm0|ymm1|ymm2|ymm3|ymm4|ymm5|ymm6|ymm7|ymm8|ymm9|ymm10|ymm11|ymm12|ymm13|ymm14|ymm15|cs|es|ds|ss|fs|gs)\b</string>
			<key>name</key>
			<string>instruction.register</string>
			<?st0是非masm语法,但是st(0)不能被匹配,所以懒的管了?>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.asm</string>
	<key>uuid</key>
	<string>801E0F36-8200-4FE7-BCBC-D371EE9B15C7</string>
</dict>
</plist>
